version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USER=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DB=calibre
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data:
